config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'static_pages#home'

  # static pages
  StaticPagesController.action_methods.each do |action|
    get "/#{action}", to: "static_pages##{action}", as: "#{action}_page"
  end

  resources :entrants, only: [:new, :create, :index]
end

app/models/entrant.rb
class Entrant < ActiveRecord::Base

  validates :first_name, :surname, :year, :email, :variable_symbol, :presence => true

  validates :email, :format => {:with => /\A^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,4})$\z/}
  validates :variable_symbol, uniqueness: true
  validates :year, numericality: {only_integer: true, greater_than_or_equal_to: 1900, less_than_or_equal_to: 2012}

  before_validation :generate_vs, on: :create
  after_create :send_email

  def to_mail
    "#{self.to_s} <#{self.email}>"
  end

  def to_s
    "#{self.first_name} #{self.surname}"
  end

  def email_str
    str = <<-EOF
Dobrý den,
obdrželi jsme Vaši přihlášku ze dne #{self.created_at.try(:strftime, '%d.%m.%Y %H:%M')}

Jméno a příjmení: #{ self.to_s }
Rok narození: #{ self.year }
Oddíl: #{ self.club.to_s }
Adresa: #{ self.address.to_s }

Zasíláme Vám informace k zaplacení startovného:
Číslo účtu: 1444871012/3030
Variabilní symbol: #{ self.variable_symbol }
Částka: 250 Kč

Připsání peněz na náš účet si můžete zkontrolovat na našem webu.

Děkujeme a přejeme kvalitní trénink.
Tým BeskydSki
https://behdovrchu.herokuapp.com/
EOF
    return str
  end

  private

  def generate_vs
    return unless self.variable_symbol.blank?
    begin
      vs = Time.now.strftime("%m%d%H") + rand(10000).to_s.rjust(4, '0')
    end while Entrant.exists?(variable_symbol: vs)
    self.variable_symbol = vs
  end

  def send_email
    return if self.variable_symbol[0..3].eql?('0000')
    EntrantMailer.registration(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController

  layout "application"

  def new
    @entrant = Entrant.new
  end

  def create
    @entrant = Entrant.new(entrant_params)

    if Entrant.where(archived: false).count < 300 and @entrant.save
      flash[:notice] = "Vaše přihláška byla přijata. Během jednoho dne Vám dorazí email, ve kterém najdete informace k zaplacení startovného."
      redirect_to entrants_path
    else
      render action: 'new'
    end
  end

  def index
    @entrants = Entrant.where(archived: false).order('surname ASC, first_name ASC')
  end

  private 

  def entrant_params
    params.require(:entrant).permit(:first_name, :surname, :email, :year, :club, :address, :climber, :male)
  end

end

app/controllers/static_pages_controller.rb
# encoding: utf-8
class StaticPagesController < ApplicationController

  layout 'application'

  def home
    render layout: 'welcome'
  end

  def programme
  end

  def results
  end

  def gallery
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Behdovrchu</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <!-- Header -->
    <header id="header">
      <div class="container">
        <div class="row t-container">

          <!-- Logo -->
          <div class="col-md-2" style="padding-right: 0px;">
            <div class="logo">
              <%= link_to home_page_path do %>
                <%= image_tag 'logo.jpg' %>
              <% end %>
            </div>
          </div>

          <%= render :partial => 'partials/menu' %> 

      </div> 
    </header>
    <!-- Header End -->

    <%= yield %>

    <%= render :partial => 'partials/footer' %> 

  </body>

</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Behdovrchu</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <!-- Header -->
    <header id="header">
      <div class="container">
        <div class="row t-container">

          <!-- Logo -->
          <div class="col-md-2" style="padding-right: 0px;">
            <div class="logo">
              <%= link_to home_page_path do %>
                <%= image_tag 'logo.jpg' %>
              <% end %>
            </div>
          </div>

          <%= render :partial => 'partials/menu' %> 
          
          <%= render :partial => 'partials/slider' %> 
<% if false %>
          <div class="row">
            <div class="col-md-12 right">&copy; Ondřej Schwarz</div>
          </div>
<% end %>
      </div> 

    </header>
    <!-- Header End -->

    <%= yield %>

    <%= render :partial => 'partials/footer' %> 

  </body>

</html>

app/views/partials/_covid.html.erb
<div class="f-center">
  <div class="head-info" style="font-size: 20px;">

    <h2 style="color: red; padding-top: 8"><b>ZÁVOD ZRUŠEN</b></h3>

    <p>
      Bohužel máme pro Vás nepřízivé informace. Vzhledem ke zpřísňujícím se podmínkám pro konání sportovních akcí jsme nuceni závod zrušit.
    </p>
    <p>
      Do poslední chvíle jsme doufali, že závod aspoň v nějaké omezené formě budeme moct uspořádat, ale aktuální omezení jsou již taková, že to není možné. Můžu Vás ujistit, že přípravy byly v plném proudu a většina věcí (startovní čísla, trička, startovní balíčky, zajištění pořadatelů, atp.) je již přichystána.
    </p>
    <p>
      Tak držte palce, ať se sejdeme za rok již bez omezení.
    </p>
    <p>
      tým <b>BeskydSki</b>
    </p>
  </div>
</div>

app/views/partials/_errors.html.erb
<% errors = object.errors.full_messages.uniq %>
<% m = object.class.to_s.downcase %>

<% if errors.any? %>

<div class="row">
  <div class="col-md-12">

    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      
      <strong>Nelze přihlásit:</strong>
      <ul>
        <% errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      
      </ul>
    </div>

  </div>
</div>

<div class="space20"></div> 

<% end %>

app/views/partials/_flash.html.erb
<div class="row">
  <div class="col-md-12">
    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
    <% end %>
  </div>
</div>

app/views/partials/_menu.html.erb
<div class="col-md-10">
  <div class="row space70"></div>
    <nav id="nav" role="navigation">
      <a href="#nav" title="Show navigation">Show navigation</a>
      <a href="#" title="Hide navigation">Hide navigation</a>
      <ul class="clearfix" style="padding-left: 0px !important;">
<% if false %>
        <li class="<%= 'active' if params[:action].eql?('home') %>"><%= link_to 'Úvod', home_page_url %></li>
<% end %>
        <li class="<%= 'active' if params[:action].eql?('programme') %>"><%= link_to 'Propozice', programme_page_path %></li>
        <li class="<%= 'active' if ['new', 'create'].include?(params[:action]) %>"><%= link_to 'Přihláška', new_entrant_path %></li>
        <li class="<%= 'active' if params[:action].eql?('index') %>"><%= link_to 'Seznam přihlášených', entrants_path %></li>
<% if true %>
        <li class="<%= 'active' if params[:action].eql?('results') %>"><%= link_to 'Výsledky', results_page_path %></li>
        <li class="<%= 'active' if params[:action].eql?('gallery') %>"><%= link_to 'Galerie', gallery_page_path %></li>
<% end %>
      </ul>
    </nav>
  </div> 
</div> 

app/views/partials/_titlebar.html.erb
<!-- Titlebar
================================================== -->
<section id="titlebar">
  <!-- Container -->
  <div class="container">
  
    <div class="eight columns">
      <h3 class="left"><%= title %></h3>
    </div>
    
    <div class="eight columns">
      <nav id="breadcrumbs">
        <ul>
          <li>Jste zde:</li>
          <li><%= link_to 'Domů', home_page_path %></li>
          <li><%= title %></li>
        </ul>
      </nav>
    </div>

  </div>
  <!-- Container / End -->
</section>

app/views/static_pages/home.html.erb
<!-- Content -->
<div id="content">
  <div class="container">
    <div class="f-center">
      <h2>Běh do vrchu Ráztoka - Pustevny</h2>

      <%#= render 'partials/covid' %>

    </div>
    <div class="f-hr"></div>

    <div class="row space20"></div>
    <div class="f-center">
      <div class="head-info">
        <b>V sobotu 6.12.2025 se uskutečnl 55. ročník tradičního běžeckého závodu "Běh do vrchu Ráztoka – Pustevny".</b>
      </div>
      <div class="head-info">
        Pořádá tým <b>BeskydSki</b>
      </div>
    </div>
    <div class="f-hr"></div>

    <div class="row space40"></div>
    <div class="row">
      <div class="col-md-12">
        <div class="row">

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Závod je za námi</h4></div>
            <div class="text-1">
              Děkujeme všem za účast. Jsme rádi, že zůstáváte věrni tomuto tradičnímu závodu, a již nyní Vás zveme na další ročník, který se uskuteční první sobotu v prosinci, tj. 5.12.2026.
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Výsledky závodu</h4></div>
            <div class="text-1">
              Přidali jsme na web výsledky, jsou k dispozici i ke stažení ve formátu .pdf. Více <%= link_to 'zde', results_page_path, class: 'more' %>
            </div>
          </div>
<% if false %>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              V brzké době spustíme registraci do závodu. Sledujte náš <%= link_to 'facebook - BehDoVrchu', "https://www.facebook.com/BehDoVrchu/", class: 'more', target: '_blank' %>
             </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Závod je za námi</h4></div>
            <div class="text-1">
              Děkujeme všem za účast. Jsme rádi, že zůstáváte věrni tomuto tradičnímu závodu, a již nyní Vás zveme na další ročník, který se uskuteční první sobotu v prosinci, tj. 6.12.2025.
            </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Výsledky závodu</h4></div>
            <div class="text-1">
              Přidali jsme na web výsledky, jsou k dispozici i ke stažení ve formátu .pdf. Více <%= link_to 'zde', results_page_path, class: 'more' %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Fotky ze závodu</h4></div>
            <div class="text-1">
              Přidali jsme na web odkaz na fotogalerii závodu. Více <%= link_to 'zde', gallery_page_path, class: 'more' %>
            </div>
          </div>


          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Během příštího týdne spustíme registraci do závodu. Sledujte náš <%= link_to 'facebook - BehDoVrchu', "https://www.facebook.com/BehDoVrchu/", class: 'more', target: '_blank' %>
             </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Fotky ze závodu - test</h4></div>
            <div class="text-1">
              Přidali jsme na web odkaz na fotogalerii závodu. Více <%= link_to 'zde', gallery_page_path, class: 'more' %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Tradiční trať</h4></div>
            <div class="text-1">
              Trasa závodu zůstává stále stejná: Hotel Ráztoka - Horní stanice lanové dráhy
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Zastavili jsme on-line přihlašování. Pokud máte zájem se závodu zúčastnit, určitě přijďte, přihlásit se můžete v den závodu při prezenci.
            </div>
          </div>


          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Výsledky závodu</h4></div>
            <div class="text-1">
              Přidali jsme na web výsledky, jsou k dispozici i ke stažení ve formátu .pdf. Více <%= link_to 'zde', results_page_path, class: 'more' %>
            </div>
          </div>


          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Zastavili jsme on-line přihlašování. Pokud máte zájem se závodu zúčastnit, určitě přijďte, přihlásit se můžete v den závodu při prezenci.
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Tradiční trať</h4></div>
            <div class="text-1">
              Trasa závodu zůstává stále stejná: Hotel Ráztoka - Horní stanice lanové dráhy
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Spustili jsme registraci do závodu. Pro přihlášení použijte  <%= link_to 'webový formulář', new_entrant_path, class: 'more' %>.
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Během příštího týdne spustíme registraci do závodu. Sledujte náš <%= link_to 'facebook - BehDoVrchu', "https://www.facebook.com/BehDoVrchu/", class: 'more', target: '_blank' %>
             </div>
          </div>



          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Spustili jsme registraci do závodu. Pro přihlášení použijte  <%= link_to 'webový formulář', new_entrant_path, class: 'more' %>.
            </div>
          </div>

          <div class="col-md-6">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Během příštího týdne spustíme registraci do závodu. Sledujte náš <%= link_to 'facebook - BehDoVrchu', "https://www.facebook.com/BehDoVrchu/", class: 'more', target: '_blank' %>
             </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Kreditní karta</h4></div>
            <div class="text-1">
              Při závodu byla nalezena platební karta. Pokud patřila někomu z Vás, je k dispozici u obsluhy parkoviště v Ráztoce.
            </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Snad nás Cov</h4></div>
            <div class="text-1">
              Doufáme, že si nenecháte ujít 
            </div>
          </div>
          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Zastavili jsme on-line přihlašování. Pokud máte zájem se závodu zúčastnit, můžete se ještě přihlásit v den závodu při prezenci.
            </div>
          </div>

          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Překvapení v cíli</h4></div>
            <div class="text-1">
              Vzhledem k tomu, že na Pustevny se běhá již 50 let, čeká každého z Vás v cíli památeční medaile.
            </div>
          </div>
          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Registrace do závodu</h4></div>
            <div class="text-1">
              Pondělí 2.12. je poslední den, kdy se můžete registrovat s předstihem. Tak to neodkládejte, startovní listina se plní. Pro přihlášení použijte  <%= link_to 'webový formulář', new_entrant_path, class: 'more' %>. Přihlásit se samořejmě budete moci ještě v den závodu.
            </div>
          </div>
          <div class="col-md-4">
            <div class="ic-1"><span><i class="fa fa-paperclip"></i></span></div>
            <div class="title-1"><h4>Kapacita závodu</h4></div>
            <div class="text-1">
              Vzhledem k loňské vysoké účasti jsme se rozhodli navýšit limit pro počet startujících v hlavním závodě na 350.
            </div>
          </div>
<% end %>

        </div>   
      </div>   

    <div class="space50"></div> 

  </div>
</div>
<!-- Content End -->

app/views/static_pages/programme.html.erb
<%= render :partial => 'partials/titlebar', locals: {title: 'Propozice'} %>

<% 
  data = []
  data << {key: 'Datum konání', value: '<b>sobota 6.12.2025</b>'}
  data << {key: 'Start závodu', value: '12:00, hromadný'}
  data << {key: 'Trať závodu', value: '<b>Beží se od Hotelu Ráztoka po Knížecí cestě do prostoru horní stanice lanové dráhy. Délka trati je 5700&nbsp;m, převýšení je 400&nbsp;m.</b>'}
  data << {key: 'Prezence', value: 'Probíhá v den závodu před Hotelem Ráztoka a to od 9:00 do 11:00.'}
  data << {key: 'Startovné', value: 'Při přihlášení a zaplacení předem <b>250 Kč</b> (platba musí přijít na účet do <b>4.12.2025</b> včetně), po tomto termínu a&nbsp;v&nbsp;den závodu <b>300 Kč</b>.'}
  data << {key: 'Přihlášky', value: "Přihlašujte se prostřednictvím <a href=#{new_entrant_path} class='more'>webového formuláře</a>. Po odeslání formuláře obdržíte email s platebními údaji. (Máte-li zájem o hromadnou přihlášku, kontaktujte nás prosím emailem.)"}

  data_small = []
  data_small << {key: 'Datum konání', value: '<b>sobota 6.12.2025</b>'}
  data_small << {key: 'Start závodu', value: '10:00, hromadný'}
  data_small << {key: 'Trať závodu', value: 'Beží se od Hotelu Ráztoka ke spodní stanici lanové dráhy. Délka trati je 600m.'}
  data_small << {key: 'Prezence', value: 'Probíhá v den závodu v bufetu Hotelu Ráztoka a to od 8:30 do 9:30.'}
  data_small << {key: 'Startovné', value: 'Dětský závod je bez startovného.'}
  data_small << {key: 'Přihlášky', value: 'Přihlašuje se na místě v den závodu při prezentaci. V případě, že se chystáte přijet s větší skupinou dětí, dejte nám, prosím, vědět na náš email.'}
%>

<!-- Content -->
<div id="content">
  <div class="container">

    <!-- Hlavni zavod -->
    <div class="row">
      <div class="col-md-12">

        <%#= render 'partials/covid' %>

        <h2>Hlavní závod</h2>

        <div class="row">
          <div class="col-md-12">

            <% data.each do |d| %>
              <div class="bs-callout bs-callout-danger">
                <h4><%= d[:key] %></h4>
                <p><%= raw d[:value] %></p>
              </div>
            <% end %>

            <h3>Kategorie</h3>

            <div class="col-md-8 col-md-offset-2">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="col-md-1" colspan="2">Kategorie</th>
                    <th class="col-md-3">Věk</th>
                    <th class="col-md-3">Ročník narození</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class='even'>
                    <td class="center">Muži</td>
                    <td class="center">J</td>
                    <td class="center">17 let a méně</td>
                    <td class="center">2008 a mladší</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Muži</td>
                    <td class="center">A</td>
                    <td class="center">18 - 39 let</td>
                    <td class="center">1986 - 2007</td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Muži</td>
                    <td class="center">B</td>
                    <td class="center">40 - 49 let</td>
                    <td class="center">1976 - 1985</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Muži</td>
                    <td class="center">C</td>
                    <td class="center">50 - 59 let</td>
                    <td class="center">1966 - 1975/td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Muži</td>
                    <td class="center">D</td>
                    <td class="center">60 let a více</td>
                    <td class="center">1965 a starší</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Ženy</td>
                    <td class="center">ZJ</td>
                    <td class="center">17 let a méně</td>
                    <td class="center">2008 a mladší</td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Ženy</td>
                    <td class="center">ZA</td>
                    <td class="center">18 - 39 let</td>
                    <td class="center">1986 - 2007</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Ženy</td>
                    <td class="center">ZB</td>
                    <td class="center">40 let a více</td>
                    <td class="center">1985 a starší</td>
                  </tr>  
                </tbody>
              </table>
            </div>

            <h3>Doplňující informace</h3>
            <ul class="list-a">
              <li><b>Limit v hlavním závodě je 300 startujících</b></li>
              <li>Každý <b>předem přihlášený</b> závodník obdrží při prezentaci tradiční tričko (při přihlášení na místě pouze do vydání zásob)</li>
              <li><b>Startovní číslo musí být umístěno viditelně na prsou</b></li>
              <li>Pro závodníky bude zajištěn vývoz oblečení na Pustevny</li>
              <li>V cíli bude pro závodníky zajištěn čaj</li>
              <li>Vyhlášení závodu bude probíhat na Pustevnách v prostoru cíle přibližně ve 14:00</li>
              <li>Parkování aut je možné na veřejných parkovištích v Ráztoce</li>
              <li><b>Každý závodník startuje na vlastní nebezpečí</b></li>
              <li>Závod se koná za každého počasí</li>
            </ul>   

          </div>
        </div>

      </div>
    </div>
      <!-- HLavni zavod End -->

    <!-- Maly zavod -->
    <div class="row">
      <div class="col-md-12">
        <h2>Závod dětí</h2>

        <div class="row">
          <div class="col-md-12">

            <% data_small.each do |d| %>
              <div class="bs-callout bs-callout-danger">
                <h4><%= d[:key] %></h4>
                <p><%= raw d[:value] %></p>
              </div>
            <% end %>

            <h3>Kategorie</h3>

            <div class="col-md-8 col-md-offset-2">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="col-md-1" colspan="2">Kategorie</th>
                    <th class="col-md-3">Věk</th>
                    <th class="col-md-3">Ročník narození</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class='even'>
                    <td class="center">Děti</td>
                    <td class="center">M</td>
                    <td class="center">1 - 5 let</td>
                    <td class="center">2020 - 2024</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Chlapci</td>
                    <td class="center">O</td>
                    <td class="center">6 - 7 let</td>
                    <td class="center">2018 - 2019</td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Chlapci</td>
                    <td class="center">P</td>
                    <td class="center">8 - 10 let</td>
                    <td class="center">2015 - 2017</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Chlapci</td>
                    <td class="center">R</td>
                    <td class="center">11 - 13 let</td>
                    <td class="center">2012 - 2014</td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Dívky</td>
                    <td class="center">S</td>
                    <td class="center">6 - 7 let</td>
                    <td class="center">2018 - 2019</td>
                  </tr>  
                  <tr class='odd'>
                    <td class="center">Dívky</td>
                    <td class="center">T</td>
                    <td class="center">8 - 10 let</td>
                    <td class="center">2015 - 2017</td>
                  </tr>  
                  <tr class='even'>
                    <td class="center">Dívky</td>
                    <td class="center">U</td>
                    <td class="center">11 - 13 let</td>
                    <td class="center">2012 - 2014</td>
                  </tr>  
                </tbody>
              </table>
            </div>

            <h3>Doplňující informace</h3>
            <ul class="list-a">
              <li>Vyhlášení závodu bude probíhat v před Hotelem Ráztoka ihned po závodě (po přesunutí závodníků zpět do Ráztoky)</li>
              <li><b>Každý závodník startuje na vlastní nebezpečí</b></li>
              <li>Závod se koná za každého počasí</li>
              <li>Děti můžou běžet v doprovodu rodičů</li>
            </ul>   


          </div>

        </div>
      </div>

    </div>
    <!-- Maly zavod End -->

    <div class="space50"></div> 

  </div>
</div>
<!-- Content End -->